<?php
// vtiger CRM configuration — generated by entrypoint from environment variables.
// Do not edit this file directly; edit config.inc.php.tpl instead.

$dbconfig['db_server']   = '${DB_HOST}';
$dbconfig['db_port']     = '${DB_PORT}';
$dbconfig['db_username'] = '${DB_USER}';
$dbconfig['db_password'] = '${DB_PASSWORD}';
$dbconfig['db_name']     = '${DB_NAME}';
$dbconfig['db_type']     = 'mysqli';
$dbconfig['db_driver']   = 'PearDatabase';

$site_URL          = '${VTIGER_SITE_URL}';
$root_directory    = '/var/www/html/';
$default_timezone  = '${VTIGER_TIMEZONE}';
$default_language  = '${VTIGER_LANGUAGE}';
$default_charset   = 'UTF-8';
$currency_name     = '${VTIGER_CURRENCY}';

$application_unique_key = '${VTIGER_ADMIN_USER}';
$admin_email            = '${VTIGER_ADMIN_EMAIL}';

$log4php_config_dir = 'log4php.properties';
$sugar_version      = '8.3.0';
$sugar_flavor       = 'VT';

// Performance
$cache_dir = 'cache/';
